version: '3.5'

services:
    backend:
        build: ./backend
        ports:
            - '5000:5000'
        expose:
            - '5000'
        depends_on:
            - mongo
        volumes:
            - ./backend:/home/pagie
        networks:
            - app_net
        env_file:
            - .env
        command: gunicorn -w 4 -b :5000 --access-logfile - --error-logfile - pagie:app
    frontend:
        build: ./frontend-material
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./logs/nginx:/var/log/nginx/
        depends_on:
            - backend
        networks:
            - app_net
    mongo:
        image: mongo:latest
        container_name: "mongo"
        environment:
            - MONGO_DATA_DIR=/usr/data/db
            - MONGO_LOG_DIR=/logs
            - MONGO_INITDB_ROOT_USERNAME=foo
            - MONGO_INITDB_ROOT_PASSWORD=pass
            - MONGO_INITDB_DATABASE=pagie
        volumes:
            - ./data/db:/usr/data/db
            - ./logs/mongo:/logs/
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - '27072:27017'
        expose:
            - '27017'
        command: mongod --smallfiles --logpath=/dev/null
        networks:
            - app_net

networks:
  app_net:
    driver: "bridge"
