version: '3.5'

services:
    backend:
        build: ./backend
        ports:
            - '5000:5000'
        expose:
            - '5000'
        depends_on:
            - mongo
        volumes:
            - ./backend:/home/pagie
        environment:
            - ENV=development
            - PORT=5000
            - DATABASE_URL=mongodb://mongo:27017/pagiegie
        command: gunicorn -w 4 -b :5000 --access-logfile - --error-logfile - pagie:app
    mongo:
        image: mongo:latest
        container_name: "mongo"
        environment:
            - MONGO_DATA_DIR=/usr/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/usr/data/db
        expose:
            - '27017'
        command: mongod --smallfiles --logpath=/dev/null # --quiet
